wordpress:
  dplyname: wpdply
  replicas: 3
  lbname: wplb
  port: 30001
  pvc:
    name: wordpress-pvc
    size: 5

db:
  dplyname: "dbdply"
  replicas: 1
  lbname: dblb
  username: user1
  database: wordpressdb
  secret:
    name: wordpress-mysql-secret
    userpass: u5erpa55
    rootpass: r00tpa55
  pvc:
    name: mysql-pvc
    size: 5
