apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
  type: {{ .Values.service.type }}
