apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" .  }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    matchLabels:
      app:  {{ .Values.labels.app }}
      tier:  {{ .Values.labels.tier }}
  strategy:
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        tier: {{ .Values.labels.tier }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name: {{ .Values.labels.app }}
        env:
        - name: MYSQL_DB_HOST
          value: wordpress-mysql
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ .Values.service.name}}
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
    volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

