apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels: 
    app: {{ .Values.labels.app }}
spec:
  accessModes: {{ .Values.accessModes }}
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
